journey
    title Histórias de Usuário — App BookEasy
    section Cadastro
      Administradora cadastra novos membros: 5: Administradora
      Administradora registra novos livros no acervo: 5: Administradora

    section Consulta e Empréstimo
      Membro consulta o catálogo de livros disponíveis: 4: Membro
      Membro solicita o empréstimo de um livro: 5: Membro
      Membro devolve um livro emprestado: 5: Membro

    section Controle e Relatórios
      Administradora visualiza empréstimos em atraso: 4: Administradora
      Administradora gera relatório de livros mais populares: 5: Administradora

    section Acesso e Histórico
      Usuário realiza login seguro no sistema: 5: Membro, Administradora
      Membro visualiza histórico de empréstimos realizados: 4: Membro
      Membro recebe notificação quando um livro reservado fica disponível: 5: Membro
