usecaseDiagram
actor "Membro do Clube" as M
actor "Administrador" as A

rectangle Sistema {
    usecase "Consultar Catálogo" as UC1
    usecase "Realizar Empréstimo" as UC2
    usecase "Devolver Livro" as UC3
    usecase "Cadastrar Novo Livro" as UC4
    usecase "Cadastrar Novo Membro" as UC5
    usecase "Gerar Relatório de Popularidade" as UC6
}

M --> UC1
M --> UC2
M --> UC3

A --> UC1
A --> UC2
A --> UC3
A --> UC4
A --> UC5
A --> UC6
